name: "Mark issues and pull requests as idle"
on:
  schedule:
    - cron: "49 11,21 * * *"

jobs:
  idle-issues-prs:
    uses: mdn/workflows/.github/workflows/idle.yml@main
    with:
      target-repo: schalkneethling/minimalist
